import { useEffect, useMemo, useState } from "react";
import "./App.css";

const PRODUCTION_API = "https://sqlmind-ai-7c0y.onrender.com";

const API_URL = (
  import.meta.env.VITE_API_URL ||
  (window.location.hostname === "localhost" ||
  window.location.hostname === "127.0.0.1"
    ? "http://127.0.0.1:8000"
    : PRODUCTION_API)
).replace(/\/+$/, "");

const features = [
  {
    icon: "NL",
    title: "Natural Language",
    text: "Ask database questions normally without manually writing SQL queries.",
    number: "01"
  },
  {
    icon: "AI",
    title: "AI SQL Agent",
    text: "The agent understands schemas, generates SQL and explains database results.",
    number: "02"
  },
  {
    icon: "✓",
    title: "Safe Queries",
    text: "SQL validation blocks destructive operations before execution.",
    number: "03"
  }
];

const workflow = [
  {
    icon: "?",
    title: "Question",
    text: "Ask your database a question using natural language."
  },
  {
    icon: "DB",
    title: "Schema",
    text: "The agent understands tables, columns and database relationships."
  },
  {
    icon: "SQL",
    title: "Generate",
    text: "The AI generates a read-only SQL query."
  },
  {
    icon: "✓",
    title: "Execute",
    text: "The validated query runs safely against the database."
  },
  {
    icon: "AI",
    title: "Answer",
    text: "SQLMind explains the database result in natural language."
  }
];

const faqs = [
  {
    question: "What is SQLMind AI?",
    answer:
      "SQLMind AI is an AI-powered Text-to-SQL agent that converts natural-language questions into SQL queries, executes safe read-only queries and explains the results."
  },
  {
    question: "Do I need to know SQL?",
    answer:
      "No. You can ask questions using normal language. SQLMind generates the SQL query automatically."
  },
  {
    question: "Is the database read-only?",
    answer:
      "Yes. SQLMind is designed to execute SELECT queries only. Destructive database operations are blocked by the validation layer."
  },
  {
    question: "What database does the demo use?",
    answer:
      "The live demo uses the Chinook SQLite database containing music-store data such as customers, invoices, artists, albums and tracks."
  },
  {
    question: "Can I see the generated SQL?",
    answer:
      "Yes. Query responses display the SQL generated by the AI agent together with the database result and natural-language explanation."
  },
  {
    question: "Can I explore individual tables?",
    answer:
      "Yes. The Database section loads the available tables and row counts from the connected backend."
  }
];

function App() {
  const [question, setQuestion] = useState("");
  const [queryResult, setQueryResult] = useState(null);
  const [queryLoading, setQueryLoading] = useState(false);
  const [queryError, setQueryError] = useState("");

  const [database, setDatabase] = useState(null);
  const [databaseLoading, setDatabaseLoading] = useState(true);
  const [databaseError, setDatabaseError] = useState("");

  const [backendOnline, setBackendOnline] = useState(false);
  const [openFaq, setOpenFaq] = useState(0);

  const totalRows = useMemo(() => {
    if (!database?.tables) return 0;
    return database.tables.reduce(
      (total, table) => total + Number(table.rows || 0),
      0
    );
  }, [database]);

  const fetchDatabase = async () => {
    setDatabaseLoading(true);
    setDatabaseError("");

    try {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 20000);

      const response = await fetch(`${API_URL}/database`, {
        method: "GET",
        signal: controller.signal,
        headers: {
          Accept: "application/json"
        }
      });

      clearTimeout(timeout);

      if (!response.ok) {
        throw new Error(`Backend returned ${response.status}`);
      }

      const data = await response.json();

      if (!data || !Array.isArray(data.tables)) {
        throw new Error("Invalid database response.");
      }

      setDatabase(data);
      setBackendOnline(true);
    } catch (error) {
      setBackendOnline(false);

      if (error.name === "AbortError") {
        setDatabaseError("Backend request timed out.");
      } else {
        setDatabaseError(
          error.message || "Database information could not be loaded."
        );
      }
    } finally {
      setDatabaseLoading(false);
    }
  };

  const checkBackend = async () => {
    try {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 15000);

      const response = await fetch(`${API_URL}/health`, {
        signal: controller.signal
      });

      clearTimeout(timeout);

      if (!response.ok) {
        throw new Error("Backend offline");
      }

      setBackendOnline(true);
    } catch {
      setBackendOnline(false);
    }
  };

  useEffect(() => {
    checkBackend();
    fetchDatabase();
  }, []);

  const executeQuery = async (customQuestion) => {
    const finalQuestion = (customQuestion ?? question).trim();

    if (!finalQuestion) {
      setQueryError("Please enter a database question.");
      return;
    }

    setQuestion(finalQuestion);
    setQueryLoading(true);
    setQueryError("");
    setQueryResult(null);

    try {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 90000);

      const response = await fetch(`${API_URL}/query`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json"
        },
        signal: controller.signal,
        body: JSON.stringify({
          question: finalQuestion
        })
      });

      clearTimeout(timeout);

      const data = await response.json();

      if (!response.ok) {
        throw new Error(
          data?.detail || `Request failed with status ${response.status}`
        );
      }

      setQueryResult(data);
      setBackendOnline(true);
    } catch (error) {
      setBackendOnline(false);

      if (error.name === "AbortError") {
        setQueryError(
          "The request took too long. The backend may be waking up. Please try again."
        );
      } else {
        setQueryError(error.message || "Request failed.");
      }
    } finally {
      setQueryLoading(false);
    }
  };

  const scrollTo = (id) => {
    document.getElementById(id)?.scrollIntoView({
      behavior: "smooth",
      block: "start"
    });
  };

  const handleKeyDown = (event) => {
    if (event.key === "Enter" && (event.ctrlKey || event.metaKey)) {
      executeQuery();
    }
  };

  return (
    <div className="app">
      <header className="navbar">
        <div className="nav-inner">
          <button className="brand" onClick={() => scrollTo("home")}>
            <div className="brand-icon">SQL</div>
            <div>
              <div className="brand-name">SQLMind AI</div>
              <div className="brand-subtitle">AI-Powered Data Analyst</div>
            </div>
          </button>

          <nav className="nav-links">
            <button onClick={() => scrollTo("features")}>Features</button>
            <button onClick={() => scrollTo("use-cases")}>Use Cases</button>
            <button onClick={() => scrollTo("preview")}>Preview</button>
            <button onClick={() => scrollTo("faq")}>FAQ</button>
          </nav>

          <div className={`backend-status ${backendOnline ? "online" : "offline"}`}>
            <span />
            {backendOnline ? "Backend Online" : "Backend Offline"}
          </div>
        </div>
      </header>

      <main>
        <section id="home" className="hero section">
          <div className="hero-grid" />

          <div className="hero-content">
            <div className="eyebrow">
              <span className="eyebrow-dot" />
              AUTONOMOUS TEXT-TO-SQL AGENT
            </div>

            <h1>
              Ask your
              <br />
              database
              <br />
              <span>anything.</span>
            </h1>

            <p className="hero-description">
              Transform natural-language questions into safe SQL, execute them
              against your database, and receive intelligent AI-powered
              answers.
            </p>

            <div className="hero-actions">
              <button
                className="primary-button"
                onClick={() => scrollTo("query")}
              >
                Start Query <span>→</span>
              </button>

              <button
                className="secondary-button"
                onClick={() => scrollTo("database")}
              >
                Explore Database
              </button>
            </div>

            <div className="hero-ready">
              <span />
              SQLMind Agent
              <small>Ctrl + Enter</small>
            </div>
          </div>

          <div className="hero-visual">
            <div className="orbital-system">
              <div className="orbit orbit-one" />
              <div className="orbit orbit-two" />
              <div className="orbit orbit-three" />
              <div className="orbit orbit-four" />

              <div className="orbit-dot dot-one" />
              <div className="orbit-dot dot-two" />
              <div className="orbit-dot dot-three" />
              <div className="orbit-dot dot-four" />

              <div className="ai-core">
                <div className="core-glow" />
                <div className="core-face">AI</div>
              </div>

              <div className="floating-card floating-sql">SQL</div>
              <div className="floating-card floating-ai">AI</div>
              <div className="floating-card floating-query">QUERY</div>
              <div className="floating-card floating-db">DATABASE</div>

              <div className="data-particle particle-one" />
              <div className="data-particle particle-two" />
              <div className="data-particle particle-three" />
              <div className="data-particle particle-four" />
              <div className="data-particle particle-five" />
              <div className="data-particle particle-six" />
            </div>
          </div>
        </section>

        <section id="features" className="section feature-section">
          <div className="section-heading">
            <div className="section-label">INTELLIGENT DATA INTERACTION</div>
            <h2>From question to insight.</h2>
            <p>
              SQLMind connects natural language, AI agents, database tools and
              secure SQL execution.
            </p>
          </div>

          <div className="feature-grid">
            {features.map((feature) => (
              <div className="feature-card" key={feature.number}>
                <div className="feature-icon">{feature.icon}</div>
                <div className="feature-number">{feature.number}</div>
                <h3>{feature.title}</h3>
                <p>{feature.text}</p>
              </div>
            ))}
          </div>
        </section>

        <section id="use-cases" className="section workflow-section">
          <div className="section-heading">
            <div className="section-label">HOW IT WORKS</div>
            <h2>
              From natural language to
              <br />
              answer.
            </h2>
            <p>
              SQLMind turns a simple question into a validated database result.
            </p>
          </div>

          <div className="workflow-grid">
            {workflow.map((item, index) => (
              <div className="workflow-card" key={item.title}>
                <div className="workflow-number">
                  {String(index + 1).padStart(2, "0")}
                </div>
                <div className="workflow-icon">{item.icon}</div>
                <h3>{item.title}</h3>
                <p>{item.text}</p>
              </div>
            ))}
          </div>
        </section>

        <section id="preview" className="section preview-section">
          <div className="section-heading">
            <div className="section-label">PRODUCT PREVIEW</div>
            <h2>See SQLMind think.</h2>
            <p>From natural-language questions to safe SQL and database insights.</p>
          </div>

          <div className="preview-grid">
            <div className="preview-window">
              <div className="window-header">
                <div className="window-dots">
                  <span />
                  <span />
                  <span />
                </div>
                <span>SQLMind AI</span>
              </div>

              <div className="preview-content">
                <div className="mini-label">NATURAL LANGUAGE</div>
                <h3>Which customers spent the most?</h3>

                <button
                  className="preview-input"
                  onClick={() =>
                    executeQuery("Which customers spent the most?")
                  }
                >
                  Ask SQLMind <span>→</span>
                </button>

                <div className="preview-ready">
                  <span />
                  AI Agent Ready
                </div>
              </div>
            </div>

            <div className="preview-window">
              <div className="window-header">
                <div className="window-dots">
                  <span />
                  <span />
                  <span />
                </div>
                <span>AI Agent</span>
              </div>

              <div className="agent-steps">
                <div>✓ Understanding database schema</div>
                <div>✓ Generating safe SQL</div>
                <div>✓ Validating query</div>
                <div>✓ Executing read-only query</div>
                <div className="agent-result">
                  {database
                    ? `${database.tables?.length || 0} database tables connected`
                    : "Database connection"}
                </div>
              </div>
            </div>

            <div className="preview-window">
              <div className="window-header">
                <div className="window-dots">
                  <span />
                  <span />
                  <span />
                </div>
                <span>Generated SQL</span>
              </div>

              <pre className="sql-preview">
{`-- READ ONLY QUERY

SELECT CustomerId,
       SUM(Total) AS spending
FROM Invoice
GROUP BY CustomerId
ORDER BY spending DESC;`}
              </pre>

              <div className="readonly-badge">READ ONLY</div>
            </div>
          </div>
        </section>

        <section id="query" className="section query-section">
          <div className="section-heading query-heading">
            <div className="section-label">AI DATA WORKSPACE</div>
            <h2>Query your database.</h2>
            <p>
              Ask SQLMind a question and let the agent generate and execute SQL.
            </p>
          </div>

          <div className="query-panel">
            <div className="query-panel-top">
              <div className="query-status">
                <span />
                SQLMind Agent Ready
              </div>
              <div className="keyboard-hint">Ctrl + Enter</div>
            </div>

            <div className="query-input-row">
              <div className="query-symbol">✦</div>

              <input
                value={question}
                onChange={(event) => setQuestion(event.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="Ask your database anything..."
              />

              <button
                className="primary-button query-button"
                onClick={() => executeQuery()}
                disabled={queryLoading}
              >
                {queryLoading ? "Thinking..." : "Ask"} <span>→</span>
              </button>
            </div>

            <div className="suggestion-row">
              <button onClick={() => setQuestion("How many customers?")}>
                How many customers?
              </button>
              <button onClick={() => setQuestion("Who is the top artist?")}>
                Top artist
              </button>
              <button onClick={() => setQuestion("How many invoices are there?")}>
                Invoice count
              </button>
              <button onClick={() => setQuestion("How many tracks are there?")}>
                Track count
              </button>
            </div>

            <div className="query-panel-bottom">
              <span>Natural language → SQL → Database → Answer</span>

              <button
                className="secondary-button"
                onClick={() => executeQuery()}
                disabled={queryLoading}
              >
                Ask SQLMind <span>→</span>
              </button>
            </div>
          </div>

          {queryError && (
            <div className="error-panel">
              <div className="error-icon">!</div>
              <div>
                <strong>Request failed</strong>
                <p>{queryError}</p>
              </div>
            </div>
          )}

          {queryResult && (
            <div className="query-result">
              <div className="result-header">
                <div>
                  <div className="section-label">AI RESPONSE</div>
                  <h3>Database insight</h3>
                </div>
                <div className="execution-time">
                  {Number(queryResult.execution_time || 0).toFixed(2)}s
                </div>
              </div>

              <div className="result-answer">
                {queryResult.answer}
              </div>

              {queryResult.sql && (
                <div className="result-block">
                  <div className="result-block-title">GENERATED SQL</div>
                  <pre>{queryResult.sql}</pre>
                </div>
              )}

              {queryResult.result && (
                <div className="result-block">
                  <div className="result-block-title">DATABASE RESULT</div>
                  <pre>{JSON.stringify(queryResult.result, null, 2)}</pre>
                </div>
              )}
            </div>
          )}
        </section>

        <section id="database" className="section database-section">
          <div className="database-header">
            <div>
              <div className="section-label">DATABASE</div>
              <h2>Chinook SQLite.</h2>
              <p>Explore the database connected to SQLMind AI.</p>
            </div>

            <button
              className="secondary-button"
              onClick={fetchDatabase}
              disabled={databaseLoading}
            >
              {databaseLoading ? "Loading..." : "Refresh Database"}
            </button>
          </div>

          <div className="database-card">
            {databaseLoading ? (
              <div className="database-loading">
                <div className="loader" />
                <div>
                  <strong>Connecting to database...</strong>
                  <p>
                    Loading schema information from the SQLMind backend.
                  </p>
                </div>
              </div>
            ) : databaseError ? (
              <div className="database-error">
                <div className="database-error-icon">!</div>

                <div>
                  <strong>Database unavailable</strong>
                  <p>
                    Database information could not be loaded from the backend.
                  </p>
                  <small>{databaseError}</small>

                  <button
                    className="primary-button retry-button"
                    onClick={fetchDatabase}
                  >
                    Try Again
                  </button>
                </div>
              </div>
            ) : (
              <>
                <div className="database-stats">
                  <div>
                    <span>Database</span>
                    <strong>{database.database || "Chinook SQLite"}</strong>
                  </div>

                  <div>
                    <span>Tables</span>
                    <strong>{database.table_count || 0}</strong>
                  </div>

                  <div>
                    <span>Total Rows</span>
                    <strong>{totalRows.toLocaleString()}</strong>
                  </div>

                  <div>
                    <span>Status</span>
                    <strong className="status-text">Connected</strong>
                  </div>
                </div>

                <div className="table-list">
                  {database.tables.map((table) => (
                    <div className="table-row" key={table.name}>
                      <div className="table-name">
                        <div className="table-icon">DB</div>
                        <span>{table.name}</span>
                      </div>

                      <div className="table-rows">
                        {Number(table.rows).toLocaleString()} rows
                      </div>
                    </div>
                  ))}
                </div>
              </>
            )}
          </div>
        </section>

        <section id="faq" className="section faq-section">
          <div className="faq-layout">
            <div className="faq-title">
              <div className="section-label">FAQ</div>
              <h2>
                Frequently
                <br />
                asked
                <br />
                questions.
              </h2>
              <p>Everything you need to know about SQLMind AI.</p>
            </div>

            <div className="faq-list">
              {faqs.map((faq, index) => (
                <div
                  className={`faq-item ${openFaq === index ? "open" : ""}`}
                  key={faq.question}
                >
                  <button
                    onClick={() =>
                      setOpenFaq(openFaq === index ? -1 : index)
                    }
                  >
                    <span>{faq.question}</span>
                    <span>{openFaq === index ? "−" : "+"}</span>
                  </button>

                  {openFaq === index && (
                    <div className="faq-answer">{faq.answer}</div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="section cta-section">
          <div className="cta-glow" />

          <div className="section-label">READY TO QUERY?</div>

          <h2>
            Ask your database
            <br />
            anything.
          </h2>

          <p>Turn natural-language questions into intelligent database insights.</p>

          <button
            className="primary-button cta-button"
            onClick={() => scrollTo("query")}
          >
            Start Query <span>→</span>
          </button>
        </section>
      </main>

      <footer className="footer">
        <div className="footer-brand">
          <div className="brand-icon">SQL</div>
          <div>
            <strong>SQLMind AI</strong>
            <span>AI-Powered Data Analyst</span>
          </div>
        </div>

        <div className={`footer-status ${backendOnline ? "online" : "offline"}`}>
          <span />
          {backendOnline ? "Backend Online" : "Backend Offline"}
        </div>

        <div className="footer-tech">
          Built with FastAPI, Gemini, React and SQLite.
        </div>
      </footer>
    </div>
  );
}

export default App;